// vue-src/src/components/Login.vue
<template>
  <div class="Login">
    <div class="container theme-showcase" role="main">

      <!-- Login -->
      <form class="form-signin well" v-on:submit.prevent="submit">
        <legend>Fazer login</legend>
        <label for="inputUsername" class="sr-only">Usuário</label>
        <input v-model="credentials.username" type="text" id="inputUsername" class="form-control" placeholder="Nome de Usuário" required autofocus name="username">
        <label for="inputPassword" class="sr-only">Senha</label>
        <input v-model="credentials.password" type="password" id="inputPassword" class="form-control" placeholder="Senha" required name="password">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Fazer login</button>
      </form>

    </div>
    <!-- /container -->
  </div>
</template>

<script>
  import auth from '../auth'

  export default {

    data() {
      return {
        credentials: {
          username: '',
          password: ''
        },
        error: ''
      }
    },

    methods: {

      submit() {

        var credentials = {
          username: this.credentials.username,
          password: this.credentials.password
        }

        auth.login(this, credentials, '/dashboard')

      }
    }

  }
</script>

// angular-src/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';
import { FlashMessagesService } from 'angular2-flash-messages';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  username: String;
  password: String;

  constructor(
    private authService: AuthService,
    private flashMessage: FlashMessagesService,
    private router: Router
  ) { }

  ngOnInit() { }

  onLoginSubmit() {
    const user = {
      username: this.username,
      password: this.password
    };

    this.authService.authenticateUser(user).subscribe(data => {
      if (data.success) {
        this.authService.storeUserData(data.token, data.user);
        this.flashMessage.show('You are now logged in', { cssClass: 'alert-success', timeout: 3000 });
        this.router.navigate(['/dashboard']);
      } else {
        this.flashMessage.show(data.msg, { cssClass: 'alert-danger', timeout: 3000 });
        this.router.navigate(['/login']);
      }
    });

    return true;
  }
}

<div class="container theme-showcase" role="main">

  <!-- Login -->
  <form class="form-signin well" (submit)="onLoginSubmit()">
    <legend>Fazer login</legend>
    <label for="inputUsername" class="sr-only">Usuário</label>
    <input type="text" id="inputUsername" class="form-control" placeholder="Nome de Usuário" required autofocus [(ngModel)]="username"
      name="username">
    <label for="inputPassword" class="sr-only">Senha</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Senha" required [(ngModel)]="password" name="password">
    <button class="btn btn-lg btn-primary btn-block" type="submit">Fazer login</button>
  </form>

</div>
<!-- /container -->
